# Tolerância para o rosto estar centralizado (15% da largura/altura da imagem)
FACE_CENTER_TOLERANCE_X = 0.15
FACE_CENTER_TOLERANCE_Y = 0.15
# Tolerância para o tamanho do rosto (entre 50% e 85% da altura da imagem)
FACE_SIZE_MIN_RATIO = 0.50
FACE_SIZE_MAX_RATIO = 0.85

MAX_SHARPNESS = 500
IDEAL_BRIGHTNESS = 140
MAX_BRIGHTNESS_DIFFERENCE = 140
MAX_EYE_ALIGNMENT_DIFFERENCE = 0.05

SHARPNESS_WEIGHT = 0.20
BRIGHTNESS_WEIGHT = 0.15
FACE_WEIGHT = 0.20